### ISSUE TITLE
React Docs

### ISSUE THREAD

**Issue by abemscac** [abemscac/pies-doc#87]
We'll use this issue&branch to collect all PRs of React docs (eng ver. only), so that we can release them all at once.

**Comment by adi-uchiha** [comment]
Can you please:- 
1.give a better description of the issue
2. Mark this issue as 'hactoberfest-accepted'
3. And assign me

**Comment by abemscac** [comment]
Hi @adi-uchiha 

Welcome! Thank you for your interest in this project!
Sorry if everything seems unclear; I have not written the contribution guide yet.
I didn't really expect somebody would be interested in this project, so I only planned to write contribution guide after both Vue 3 and React docs are done.

This issue is created merely for issue number; we need a branch to temporarily merge all React docs related stuff, so that we can publish them (merge them back to `main`) all at once when they're done.
Since PiesDoc is a documentation, it's really up to the author to decide what he/she wants to tell the reader.
We have some topics defined in #26, and in there you can find the React section.

![Screen Shot 2022-09-30 at 6 22 08 PM](https://user-images.githubusercontent.com/59676941/193250777-b9bde0b4-c4bd-499c-b45a-bd30ff2729ef.png)

All those issues are ready-to-be-implemented, I think #52 and #18 are both good first issues.
PiesDoc is built using [Docusaurus](https://docusaurus.io/), you can refer to their website for file structure, config, etc.

However, it might be difficult for you to get into this project at this stage; because even though this project is open-source, I was originally planning to finish all chapters for 1st release on my own. :sweat_smile:
If you're still interested, feel free to pick any issue and assign it to yourself!
It looks like you're participating in Hacktoberfest, which requires you to accomplish something within limited time (if I didn't get it wrong).
So it's totally fine if you decide to look for other project(s) that's more friendly to open-source contributors.
Thank you!

**Comment by adi-uchiha** [comment]
Thanks for clear description. Though this is a personal project the PR made to this project will still be counted so I'd like to contribute

**Comment by abemscac** [comment]
Sure, no problem!
Feel free to pick any issue you find interesting and assign it to yourself!
If there's any important topic you want to talk about, but not listed in #26, you can just create one on your own.
Thanks!

**Comment by adi-uchiha** [comment]
I don't think you should quit on this. Because official doc's are not for everyone.
